name: PROD Pull Request Validation

on:
  pull_request:
    branches:
      - Prod

permissions:
  contents: read
  pull-requests: write

jobs:
  terraform-plan:
    name: Terraform Plan (PROD)
    runs-on: ubuntu-latest

    env:
      ENVIRONMENT: prod

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      # Allow only ACC branch
      - name: Validate Source Branch
        run: |
          echo "Source Branch: ${{ github.head_ref }}"

          if [[ "${{ github.head_ref }}" != "Acc" ]]; then
            echo "Only Acc branch can create PR into PROD."
            exit 1
          fi

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.PROD_AWS_REGION }}

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=dev-pro_deployment
            -Dsonar.projectName=dev-pro_deployment
            -Dsonar.sources=.
            -Dsonar.exclusions=.terraform/**,**/*.tfstate,**/*.tfstate.backup,**/.terraform.lock.hcl
            
      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Identify Environment
        run: |
          echo "Environment : $ENVIRONMENT"

      - name: Terraform Plan
        run: |
          terraform plan \
            -input=false \
           

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-prod
          path: tfplan
