name: PROD Deployment

on:
  push:
    branches:
      - Prod

permissions:
  contents: read

jobs:
  terraform-apply:
    name: Terraform Apply (PROD)
    runs-on: ubuntu-latest

    environment:
      name: production

    env:
      ENVIRONMENT: prod

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.PROD_AWS_REGION }}

      - name: Identify Environment
        run: echo "Deploying to $ENVIRONMENT"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: |
          terraform apply \
            -auto-approve \
            -var-file=environments/prod.tfvars
