name: PROD Pull Request Validation

on:
  pull_request:
    branches:
      - Prod


permissions:
  contents: read
  pull-requests: write
  security-events: write

jobs:
  java-validation:
    name: Java Build, Test & Scan
    runs-on: ubuntu-latest

    env:
      ENVIRONMENT: prod
    steps:
      #################################################################
      # Checkout Repository
      #################################################################
      - name: Checkout Repository
        uses: actions/checkout@v4

      #################################################################
      # Setup Java
      #################################################################
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      #################################################################
      # Initialize CodeQL
      #################################################################
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java

      #################################################################
      # Maven Validate
      #################################################################
      - name: Maven Validate
        working-directory: spring-petclinic
        run: mvn validate
      #################################################################
      # Compile
      #################################################################
      - name: Compile Application
        working-directory: spring-petclinic
        run: mvn clean compile

      #################################################################
      # Run JUnit Tests
      #################################################################
      - name: Run Unit Tests
        working-directory: spring-petclinic
        run: mvn test

      #################################################################
      # Package Application
      #################################################################
      - name: Package JAR
        working-directory: spring-petclinic
        run: mvn package -DskipTests

      #################################################################
      # Upload JAR Artifact
      #################################################################
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-jar 
          path: target/*.jar
          
      ################################################################
      # CODE QL
      #################################################################
   
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
